version: 2

jobs:
  build:
    working_directory: ~/squanchy

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      ANDROID_HOME: /opt/android/sdk
      APPLICATION_ID: net.squanchy.example
      FABRIC_API_KEY: 0000000000000000000000000000000000000000
      ALGOLIA_APPLICATION_ID: ABCDEFGH12
      ALGOLIA_API_KEY: 00000000000000000000000000000000

    steps:
      - checkout

      # Restore cached dependencies (if any)
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      # Prepare the container for the build
      - run:
          name: Ensure Android SDK install is up-to-date
          command: .circleci/ci-scripts/ensure-sdkmanager.sh
      - run:
          name: Create mock Play Services JSON
          command: .circleci/ci-scripts/ci-mock-google-services-setup.sh

      # Run the main job commands, delegating to Gradle
      # See https://issuetracker.google.com/issues/62217354 for the parallelism option
      - run:
          name: Run static analysis
          command: ./gradlew evaluateViolations -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
      - run:
          name: Run tests
          command: ./gradlew testRelease -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

      # Store all the downloaded dependencies in the CI cache
      - save_cache:
          paths:
            # Android SDK
            - /usr/local/android-sdk-linux/tools
            - /usr/local/android-sdk-linux/platform-tools
            - /usr/local/android-sdk-linux/build-tools
            - /usr/local/android-sdk-linux/licenses
            - /usr/local/android-sdk-linux/extras/google/m2repository

            # Gradle dependencies
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      # Collect static analysis reports as build artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Collect JUnit test results
      - store_test_results:
          path: app/build/test-results
